SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/SFS_RA_Agent_Manager__c.object-meta.xml
<CustomObject>
    <description>Master Object that controls behaviour of SFS reusable assets.</description>
    <label>Agent Manager</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Agent Manager</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Additional_Considerations__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Additional_Considerations__c</fullName>
    <description>Additional Considerations to apply when selecting the appointments to check for Jeopardy</description>
    <inlineHelpText>Additional Considerations to apply when selecting the appointments to check for Jeopardy</inlineHelpText>
    <label>Additional Considerations</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Agent_Type__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Agent_Type__c</fullName>
    <label>Agent Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Jeopardy Agent</fullName>
            </value>
            <value>
                <fullName>Drip Feed</fullName>
            </value>
            <value>
                <fullName>Bulk Feed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Enabled__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Enabled__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Enabled</label>
    <type>Checkbox</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Schedule_Frequency__c</fullName>
    <label>Schedule Frequency (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Agent Managers</relationshipLabel>
    <relationshipName>Agent_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Type__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Type__c</fullName>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Controller Record</fullName>
            </value>
            <value>
                <fullName>Territory Decomposition</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/SFS_RA_Agent_Manager_Entry__c.object-meta.xml
<CustomObject>
    <description>Individual entry records for each Agent Manager</description>
    <label>Agent Manager Entry</label>
    <nameField>
        <displayFormat>AME-{000000}</displayFormat>
        <label>Agent Manager Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Manager Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Agent_Manager__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Agent_Manager__c</fullName>
    <label>Agent Manager</label>
    <referenceTo>SFS_RA_Agent_Manager__c</referenceTo>
    <relationshipLabel>Agent Manager Entries</relationshipLabel>
    <relationshipName>SFS_RA_Agent_Manager_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Based_On__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ActualStartTime</fullName>
                <label>Actual Time</label>
            </value>
            <value>
                <fullName>ArrivalWindowStartTime</fullName>
                <label>Arrival Time</label>
            </value>
            <value>
                <fullName>SchedStartTime</fullName>
                <label>Scheduled Start Time</label>
            </value>
            <value>
                <fullName>DueDate</fullName>
                <label>Due Date</label>
            </value>
            <value>
                <fullName>SchedEndTime</fullName>
                <label>Scheduled End Time</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Consider_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Consider_Travel_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consider Travel Time?</label>
    <type>Checkbox</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_End_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_End_Time__c</fullName>
    <label>End Time (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Jeopardy_Type__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Jeopardy_Type__c</fullName>
    <label>Jeopardy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Late Start Travel</fullName>
            </value>
            <value>
                <fullName>Late Completion</fullName>
            </value>
            <value>
                <fullName>Rescheduling Required</fullName>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
            </value>
            <value>
                <fullName>Late Arrival</fullName>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Sequence_No__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Sequence_No__c</fullName>
    <label>Sequence No</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Start_Time__c</fullName>
    <label>Start Time (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Status__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Status__c</fullName>
    <inlineHelpText>Status to be checked for Jeopardy.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/classes/SFS_RA_ServiceAppointmentJeopardyHelper.cls
public class SFS_RA_ServiceAppointmentJeopardyHelper {
    
    public Static Set<String> getTerritoryValues(List<SFS_RA_Agent_Manager__c> agentManagerSD){
        Set<String> territoryValues = new Set<String>();
        for(SFS_RA_Agent_Manager__c agentManagerRecord : agentManagerSD){
            territoryValues.add(agentManagerRecord.SFS_RA_Service_Territory__c);
        }
        return territoryValues;
    }
    
    public Static Set<String> getStatusValues(List<SFS_RA_Agent_Manager__c> agentManagerSD){
        Set<String> statusValues = new Set<String>();
        for(SFS_RA_Agent_Manager__c agentManagerRecord : agentManagerSD){
            if(!agentManagerRecord.SFS_RA_Agent_Manager_Entries__r.isEmpty()){
                for(SFS_RA_Agent_Manager_Entry__c agentManagerEntryRecord: agentManagerRecord.SFS_RA_Agent_Manager_Entries__r){
                    statusValues.add(agentManagerEntryRecord.SFS_RA_Status__c);
                }
            }
        }
        return statusValues;
    }
    
    public Static List<SFS_RA_Agent_Manager__c> getControllerAgentManager(){
        return [SELECT id,SFS_RA_Schedule_Frequency__c, SFS_RA_Additional_Considerations__c, SFS_RA_Batch_Size__c FROM SFS_RA_Agent_Manager__c WHERE SFS_RA_Enabled__c = true 
                AND SFS_RA_Type__c =: SFS_RA_ConstantsUtil.AM_CONTROLLER_RECORD AND SFS_RA_Agent_Type__c =: SFS_RA_ConstantsUtil.AM_AGENT_TYPE_JEOPARDY LIMIT 1];
    }
    
    public Static List<SFS_RA_Agent_Manager__c> getSDAgentManager(){
        return [SELECT id,SFS_RA_Service_Territory__c, 
                (SELECT id,SFS_RA_Enabled__c,SFS_RA_Agent_Manager__c,SFS_RA_Based_On__c,
                 SFS_RA_End_Time__c,SFS_RA_Start_Time__c,SFS_RA_Jeopardy_Type__c,
                 SFS_RA_Sequence_No__c,SFS_RA_Status__c, SFS_RA_Consider_Travel_Time__c
                 FROM SFS_RA_Agent_Manager_Entries__r where SFS_RA_Enabled__c = true ORDER BY SFS_RA_Sequence_No__c )
                FROM SFS_RA_Agent_Manager__c WHERE SFS_RA_Enabled__c = true AND SFS_RA_Type__c =: SFS_RA_ConstantsUtil.AM_TERRITORY_DECOMPOSITION
                AND SFS_RA_Agent_Type__c =: SFS_RA_ConstantsUtil.AM_AGENT_TYPE_JEOPARDY];   
    }
    
    public Static Map<Id, AssignedResource> getAssignedResourceForAppointment(List<ServiceAppointment> serviceAppointments){
        Map<Id, AssignedResource> mapOfServiceAppointmentAndAssignedResource = new Map<Id, AssignedResource>();
        List<ServiceAppointment> listOfAppointmentWithResource = new List<ServiceAppointment>();
        
        listOfAppointmentWithResource = [SELECT ID, (SELECT ID, EstimatedTravelTime FROM ServiceResources ORDER By CreatedDate) FROM ServiceAppointment WHERE ID IN :serviceAppointments];
        
        for(ServiceAppointment appointment : listOfAppointmentWithResource){
            if(!mapOfServiceAppointmentAndAssignedResource.containsKey(appointment.Id)){
                if(!appointment.ServiceResources.isEmpty()){
                    mapOfServiceAppointmentAndAssignedResource.put(appointment.Id, appointment.ServiceResources[0]);
                }
            }
        }     
        return mapOfServiceAppointmentAndAssignedResource; 
    }    
}