SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/SFS_RA_Agent_Manager__c.object-meta.xml
<CustomObject>
    <description>Master Object that controls behaviour of SFS reusable assets.</description>
    <label>Agent Manager</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Agent Manager</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Additional_Considerations__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Additional_Considerations__c</fullName>
    <description>Additional Considerations to apply when selecting the appointments to check for Jeopardy</description>
    <inlineHelpText>Additional Considerations to apply when selecting the appointments to check for Jeopardy</inlineHelpText>
    <label>Additional Considerations</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Schedule_Frequency__c</fullName>
    <label>Schedule Frequency (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Service_Territory__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Service_Territory__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Service Territory</label>
    <referenceTo>ServiceTerritory</referenceTo>
    <relationshipLabel>Agent Managers</relationshipLabel>
    <relationshipName>Agent_Managers</relationshipName>
    <type>Lookup</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/SFS_RA_Agent_Manager_Entry__c.object-meta.xml
<CustomObject>
    <description>Individual entry records for each Agent Manager</description>
    <label>Agent Manager Entry</label>
    <nameField>
        <displayFormat>AME-{000000}</displayFormat>
        <label>Agent Manager Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Manager Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Agent_Manager__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Agent_Manager__c</fullName>
    <label>Agent Manager</label>
    <referenceTo>SFS_RA_Agent_Manager__c</referenceTo>
    <relationshipLabel>Agent Manager Entries</relationshipLabel>
    <relationshipName>SFS_RA_Agent_Manager_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Based_On__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Based_On__c</fullName>
    <label>Based On</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>ActualStartTime</fullName>
                <label>Actual Time</label>
            </value>
            <value>
                <fullName>ArrivalWindowStartTime</fullName>
                <label>Arrival Time</label>
            </value>
            <value>
                <fullName>SchedStartTime</fullName>
                <label>Scheduled Start Time</label>
            </value>
            <value>
                <fullName>DueDate</fullName>
                <label>Due Date</label>
            </value>
            <value>
                <fullName>SchedEndTime</fullName>
                <label>Scheduled End Time</label>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Consider_Travel_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Consider_Travel_Time__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Consider Travel Time?</label>
    <type>Checkbox</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_End_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_End_Time__c</fullName>
    <label>End Time (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Jeopardy_Type__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Jeopardy_Type__c</fullName>
    <label>Jeopardy Type</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Late Start Travel</fullName>
            </value>
            <value>
                <fullName>Late Completion</fullName>
            </value>
            <value>
                <fullName>Rescheduling Required</fullName>
            </value>
            <value>
                <fullName>Due Date Approaching</fullName>
            </value>
            <value>
                <fullName>Late Arrival</fullName>
            </value>
            <value>
                <fullName>Delayed Start</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Start_Time__c</fullName>
    <label>Start Time (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Status__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Status__c</fullName>
    <inlineHelpText>Status to be checked for Jeopardy.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/classes/SFS_RA_ServiceAppointmentJeopardyBatch.cls
public class SFS_RA_ServiceAppointmentJeopardyBatch implements Database.Batchable<sObject>,Database.Stateful, Database.RaisesPlatformEvents {
    
    List<SFS_RA_Agent_Manager__c> agentManagerSD = new List<SFS_RA_Agent_Manager__c>();
    List<SFS_RA_Agent_Manager__c> agentManager = new List<SFS_RA_Agent_Manager__c>();
    Map<String, List<SFS_RA_Agent_Manager_Entry__c>> mapOfAgentManagerStateAndEntries = new Map<String, List<SFS_RA_Agent_Manager_Entry__c>>();
    Integer intervalMinutes;
    Integer batchSize;
        
    public Database.QueryLocator start(Database.BatchableContext BC){
        
        agentManager = SFS_RA_ServiceAppointmentJeopardyHelper.getControllerAgentManager();
        
        if(agentManager.isEmpty()){
            
            return Database.getQueryLocator(SFS_RA_ConstantsUtil.SA_BLANK_QUERY);
        }
        else{
            
            intervalMinutes = agentManager[0].SFS_RA_Schedule_Frequency__c != null ? (Integer.valueOf(agentManager[0].SFS_RA_Schedule_Frequency__c) ) : 60;
            batchSize = agentManager[0].SFS_RA_Batch_Size__c != null ? (Integer.valueOf(agentManager[0].SFS_RA_Batch_Size__c) ) : 200;
            agentManagerSD = SFS_RA_ServiceAppointmentJeopardyHelper.getSDAgentManager();
            
            if(agentManagerSD.isEmpty()){
                return Database.getQueryLocator(SFS_RA_ConstantsUtil.SA_BLANK_QUERY);
            }
            else{
                for(SFS_RA_Agent_Manager__c agentManagerRecord : agentManagerSD){
                    if(!agentManagerRecord.SFS_RA_Agent_Manager_Entries__r.isEmpty()){
                        mapOfAgentManagerStateAndEntries.put(agentManagerRecord.SFS_RA_Service_Territory__c , agentManagerRecord.SFS_RA_Agent_Manager_Entries__r);
                    }
                }
                Set<String> territoryValues = SFS_RA_ServiceAppointmentJeopardyHelper.getTerritoryValues(agentManagerSD);
                Set<String> statusValues = SFS_RA_ServiceAppointmentJeopardyHelper.getStatusValues(agentManagerSD);

                if(!statusValues.isEmpty() && !territoryValues.isEmpty()){
                    
                    String query ='SELECT Id, AppointmentNumber, SchedStartTime, SchedEndTime, DueDate ,ArrivalWindowStartTime, ActualStartTime, Status, ServiceTerritoryId, ServiceTerritory.Name, FSL__InJeopardy__c, FSL__InJeopardyReason__c FROM ServiceAppointment ';
                    query += 'WHERE Status IN: statusValues AND ServiceTerritoryId IN: territoryValues AND FSL__InJeopardy__c = FALSE';
                    
                    if(String.isNotBlank(agentManager[0].SFS_RA_Additional_Considerations__c)){
                        query += ' AND ' + agentManager[0].SFS_RA_Additional_Considerations__c;
                    }
                    
                    return Database.getQueryLocator(query);
                }
                else{
                    return Database.getQueryLocator(SFS_RA_ConstantsUtil.SA_BLANK_QUERY);
                }
            }
        }
    }
    
    public void execute(Database.BatchableContext BC, List<ServiceAppointment> serviceAppointments){
		List<ServiceAppointment> appointmentListToUpdate = new List<ServiceAppointment>();
        List<SFS_RA_Agent_Manager_Entry__c> agentManagerEntriesForTerritory = new List<SFS_RA_Agent_Manager_Entry__c>();        
        
        Map<Id, AssignedResource> mapOfServiceAppointmentAndAssignedResource = new Map<Id, AssignedResource>();
        mapOfServiceAppointmentAndAssignedResource = SFS_RA_ServiceAppointmentJeopardyHelper.getAssignedResourceForAppointment(serviceAppointments);
        
        for(ServiceAppointment appointment : serviceAppointments){
            if(mapOfAgentManagerStateAndEntries.containsKey(appointment.ServiceTerritoryId)){ 
                agentManagerEntriesForTerritory = mapOfAgentManagerStateAndEntries.get(appointment.ServiceTerritoryId);
                
                for(SFS_RA_Agent_Manager_Entry__c agentManagerEntry : agentManagerEntriesForTerritory){
                    Integer startTimeAddMinutes = agentManagerEntry.SFS_RA_Start_Time__c.intValue();
                    Integer endTimeAddMinutes   = agentManagerEntry.SFS_RA_End_Time__c.intValue();
                    
                    Datetime startTimetoCheck;
                    Datetime endTimetoCheck;
                    
                    if(appointment.get(agentManagerEntry.SFS_RA_Based_On__c)!=null){
                        
                        startTimetoCheck   = Datetime.valueOf(appointment.get(agentManagerEntry.SFS_RA_Based_On__c)).addMinutes(startTimeAddMinutes);
                        endTimetoCheck     = Datetime.valueOf(appointment.get(agentManagerEntry.SFS_RA_Based_On__c)).addMinutes(endTimeAddMinutes);
                        
                        if(agentManagerEntry.SFS_RA_Consider_Travel_Time__c == true){
                            if(mapOfServiceAppointmentAndAssignedResource.containsKey(appointment.ID)){
                                
                                //subtract the travel time
                                Integer travelTime = (mapOfServiceAppointmentAndAssignedResource.get(appointment.ID).EstimatedTravelTime != null) ? ((-1)*mapOfServiceAppointmentAndAssignedResource.get(appointment.ID).EstimatedTravelTime.intValue()) : 0 ;
                                startTimetoCheck = startTimetoCheck.addMinutes(travelTime);
                                
                            }
                        } 
                    }
                    else{
                        continue;
                    }
                    
                    if(
                        (appointment.get(SFS_RA_ConstantsUtil.SA_STATUS) == agentManagerEntry.SFS_RA_Status__c) &&
                        (Datetime.now() >= startTimetoCheck) &&
                        (Datetime.now() <= endTimetoCheck)
                    ) {
                        
                        appointment.FSL__InJeopardy__c = TRUE;
                        appointment.FSL__InJeopardyReason__c = agentManagerEntry.SFS_RA_Jeopardy_Type__c ;
                        appointmentListToUpdate.add(appointment);
                        break;
                        
                    }
                }
            }
        }
        
        if(!appointmentListToUpdate.isEmpty()){
            Database.update(appointmentListToUpdate, false);
        }
            
    }
    
    public void finish(Database.BatchableContext BC){
        if(!Test.isRunningTest())
        {
            //Schedule the batch to run again
            String jobId = System.scheduleBatch(new SFS_RA_ServiceAppointmentJeopardyBatch(), 'SFS_RA_ServiceAppointmentJeopardyBatch', intervalMinutes, batchSize);
        }
    }
}