SFS_RA - Dispatch Policy Components/force-app/main/default/objects/ServiceResource/fields/Dispatch_Policy__c.field-meta.xml
<CustomField>
    <fullName>Dispatch_Policy__c</fullName>
    <label>Dispatch Policy</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Drip Feed</fullName>
            </value>
            <value>
                <fullName>Bulk Feed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager__c/SFS_RA_Agent_Manager__c.object-meta.xml
<CustomObject>
    <description>Master Object that controls behaviour of SFS reusable assets.</description>
    <label>Agent Manager</label>
    <nameField>
        <displayFormat>AM-{00000}</displayFormat>
        <label>Agent Manager</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Managers</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Additional_Considerations__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Additional_Considerations__c</fullName>
    <description>Additional Considerations to apply when selecting the appointments to check for Jeopardy</description>
    <inlineHelpText>Additional Considerations to apply when selecting the appointments to check for Jeopardy</inlineHelpText>
    <label>Additional Considerations</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Batch_Size__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Batch_Size__c</fullName>
    <label>Batch Size</label>
    <precision>4</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager__c/fields/SFS_RA_Schedule_Frequency__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Schedule_Frequency__c</fullName>
    <label>Schedule Frequency (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/SFS_RA_Agent_Manager_Entry__c.object-meta.xml
<CustomObject>
    <description>Individual entry records for each Agent Manager</description>
    <label>Agent Manager Entry</label>
    <nameField>
        <displayFormat>AME-{000000}</displayFormat>
        <label>Agent Manager Entry</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Agent Manager Entries</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Agent_Manager__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Agent_Manager__c</fullName>
    <label>Agent Manager</label>
    <referenceTo>SFS_RA_Agent_Manager__c</referenceTo>
    <relationshipLabel>Agent Manager Entries</relationshipLabel>
    <relationshipName>SFS_RA_Agent_Manager_Entries</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Start_Time__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Start_Time__c</fullName>
    <label>Start Time (min.)</label>
    <precision>5</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

SFS_RA_JeopardyManager/force-app/main/default/objects/SFS_RA_Agent_Manager_Entry__c/fields/SFS_RA_Status__c.field-meta.xml
<CustomField>
    <fullName>SFS_RA_Status__c</fullName>
    <inlineHelpText>Status to be checked for Jeopardy.</inlineHelpText>
    <label>Status</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

SFS_RA - Dispatch Policy Components/force-app/main/default/classes/SFS_RA_ABServApptDripDisptachBatch.cls
/**
 * @description       : Make status of scheduled appointments from Scheduled to Dispatch where the assigned resource is having Drip feed as dispatch policy.
 * @author            : Laxman Singh/ Ankit Chawla
 **/
public class SFS_RA_ABServApptDripDisptachBatch implements Database.Batchable<sObject>, Database.Stateful, Database.RaisesPlatformEvents{
    
    Map<String, List<SFS_RA_Agent_Manager_Entry__c>> mapOfAgentManagerStateAndEntries = new Map<String, List<SFS_RA_Agent_Manager_Entry__c>>();
    Integer intervalMinutes;
    Integer batchSize;
    String defaultSAStatus;
    Integer timeSlotInHours;
    Datetime currentDateTime;
    Datetime endDateTime;
    
    List<SFS_RA_Agent_Manager__c> agentManager = new List<SFS_RA_Agent_Manager__c>();
    
    public Database.QueryLocator start(Database.BatchableContext bc) { 
        String dispatchPolicy = SFS_RA_ConstantsUtil.AM_AGENT_TYPE_DRIP_FEED;
        agentManager = SFS_RA_SerApptDispatchingPolicyHelper.getControllerRecordDetails(dispatchPolicy);
        if(agentManager.isEmpty()){
            return Database.getQueryLocator(SFS_RA_ConstantsUtil.AR_BLANK_QUERY);
        }
        else{
            intervalMinutes = agentManager[0].SFS_RA_Schedule_Frequency__c != null ? (Integer.valueOf(agentManager[0].SFS_RA_Schedule_Frequency__c) ) : 15;
            batchSize = agentManager[0].SFS_RA_Batch_Size__c != null ? (Integer.valueOf(agentManager[0].SFS_RA_Batch_Size__c) ) : 200;
            if(!agentManager[0].SFS_RA_Agent_Manager_Entries__r.isEmpty()){
 	  			defaultSAStatus = agentManager[0].SFS_RA_Agent_Manager_Entries__r[0].SFS_RA_Status__c != null ?	agentManager[0].SFS_RA_Agent_Manager_Entries__r[0].SFS_RA_Status__c : SFS_RA_ConstantsUtil.SA_STATUS_SCHEDULED;
                timeSlotInHours = agentManager[0].SFS_RA_Agent_Manager_Entries__r[0].SFS_RA_Start_Time__c  != null ? (Integer.valueOf(agentManager[0].SFS_RA_Agent_Manager_Entries__r[0].SFS_RA_Start_Time__c ))/60 : 2;
            }
            else{
                return Database.getQueryLocator(SFS_RA_ConstantsUtil.AR_BLANK_QUERY);
            }
        }
        currentDateTime = datetime.now();
        endDateTime = currentDateTime.addHours(timeSlotInHours);
		
        
        String query;
        //query = 'SELECT Id, ServiceAppointmentId FROM AssignedResource WHERE ServiceAppointment.Status =: defaultSAStatus AND ServiceResource.Dispatch_Policy__c =: dispatchPolicy AND (ServiceAppointment.SchedStartTime >=: currentDateTime AND ServiceAppointment.SchedStartTime <=: endDateTime)';    
		query = 'SELECT Id, ServiceAppointmentId, EstimatedTravelTime, ServiceAppointment.SchedStartTime FROM AssignedResource WHERE ServiceAppointment.Status =: defaultSAStatus AND ServiceResource.Dispatch_Policy__c =: dispatchPolicy';            
        if(String.isNotBlank(agentManager[0].SFS_RA_Additional_Considerations__c) && agentManager[0].SFS_RA_Additional_Considerations__c.contains('ServiceAppointment.SchedStartTime')){
            query += ' AND ' + agentManager[0].SFS_RA_Additional_Considerations__c;
        }
        else{
            query += ' AND ServiceAppointment.SchedStartTime = TODAY';
        }
        return Database.getQueryLocator(query);
    }

    public void execute(Database.BatchableContext bc, List<AssignedResource> scope) {
        List<ServiceAppointment> serviceAppointmentsToUpdate = new List<ServiceAppointment>();
        Set<String> serviceAppointmentsIdSet = new Set<String>();

        for(AssignedResource assignedResourceRec : scope){
            DateTime scheduledStartDateTimeWithEstimatedTravelTime = assignedResourceRec.EstimatedTravelTime != null ? assignedResourceRec.ServiceAppointment.SchedStartTime.addMinutes(-Integer.valueOf(assignedResourceRec.EstimatedTravelTime)) : assignedResourceRec.ServiceAppointment.SchedStartTime;
            if(scheduledStartDateTimeWithEstimatedTravelTime >= currentDateTime && scheduledStartDateTimeWithEstimatedTravelTime <= endDateTime) {
            	serviceAppointmentsIdSet.add(assignedResourceRec.ServiceAppointmentId); 	   
            }
        }

        for(ServiceAppointment sa : [SELECT Id, Status FROM ServiceAppointment WHERE Id IN : serviceAppointmentsIdSet]){
            sa.Status = SFS_RA_ConstantsUtil.SA_STATUS_DISPATCHED;
            serviceAppointmentsToUpdate.add(sa);
        }

        if(!serviceAppointmentsToUpdate.isEmpty()){
            List<Database.SaveResult> result = Database.update(serviceAppointmentsToUpdate, false);
        }
    }

    public void finish(Database.BatchableContext bc) {
        if(!Test.isRunningTest()){
            System.scheduleBatch(new SFS_RA_ABServApptDripDisptachBatch(), 'SA_Status_Dispatch_Update', intervalMinutes, batchSize);    
        }
    }
}